version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: avitech-app
    restart: unless-stopped
    volumes:
      - ./:/var/www
    networks:
      - avitech-net

  webserver:
    image: nginx:stable
    container_name: avitech-nginx
    restart: unless-stopped
    ports:
      - "8686:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - avitech-net

networks:
  avitech-net:
    driver: bridge
